-- Esquema de la base de datos de la biblioteca (idempotente)

CREATE TABLE IF NOT EXISTS usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    password VARCHAR(100) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    rol VARCHAR(20) NOT NULL,
    CONSTRAINT uq_usuario_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS libro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn VARCHAR(20) NOT NULL,
    titulo VARCHAR(200) NOT NULL,
    autor VARCHAR(150),
    categoria VARCHAR(100),
    stock_total INTEGER NOT NULL,
    stock_disponible INTEGER NOT NULL,
    CONSTRAINT uq_libro_isbn UNIQUE (isbn),
    CONSTRAINT ck_libro_stock CHECK (stock_total >= 0 AND stock_disponible >= 0 AND stock_disponible <= stock_total)
);

CREATE TABLE IF NOT EXISTS prestamo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    libro_id BIGINT NOT NULL,
    fecha_prestamo TIMESTAMP NOT NULL,
    fecha_devolucion_esperada TIMESTAMP NOT NULL,
    fecha_devolucion_real TIMESTAMP,
    estado VARCHAR(20) NOT NULL,
    CONSTRAINT fk_prestamo_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id),
    CONSTRAINT fk_prestamo_libro FOREIGN KEY (libro_id) REFERENCES libro (id)
);

CREATE INDEX IF NOT EXISTS idx_prestamo_usuario ON prestamo (usuario_id);
CREATE INDEX IF NOT EXISTS idx_prestamo_estado ON prestamo (estado);
